// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdSU6FIfJN9bWbdZ6mo68pg1T0My2sQs',
    appId: '1:79402290024:web:e3be93897e13731653a4dd',
    messagingSenderId: '79402290024',
    projectId: 'alu-connect-yves',
    authDomain: 'alu-connect-yves.firebaseapp.com',
    storageBucket: 'alu-connect-yves.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHB9Nyzyr3YjmhNd4O6P4h5MlJOfAf4nI',
    appId: '1:79402290024:android:fe68d70fa891d61253a4dd',
    messagingSenderId: '79402290024',
    projectId: 'alu-connect-yves',
    storageBucket: 'alu-connect-yves.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVJFook4EX8vnZ9gJte6RqvF2pnRw0FM',
    appId: '1:79402290024:ios:8bdb4c7210e9fde853a4dd',
    messagingSenderId: '79402290024',
    projectId: 'alu-connect-yves',
    storageBucket: 'alu-connect-yves.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXVJFook4EX8vnZ9gJte6RqvF2pnRw0FM',
    appId: '1:79402290024:ios:8bdb4c7210e9fde853a4dd',
    messagingSenderId: '79402290024',
    projectId: 'alu-connect-yves',
    storageBucket: 'alu-connect-yves.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcdSU6FIfJN9bWbdZ6mo68pg1T0My2sQs',
    appId: '1:79402290024:web:27bcf9f1cea47cd453a4dd',
    messagingSenderId: '79402290024',
    projectId: 'alu-connect-yves',
    authDomain: 'alu-connect-yves.firebaseapp.com',
    storageBucket: 'alu-connect-yves.firebasestorage.app',
  );
}
